version: '3'
services:
    mysqldb:
        image: 'mysql:latest'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'admin-mysqldb:/var/lib/mysql'
        networks:
            - mysqlnet
        healthcheck:
            test:
                - CMD
                - mysqladmnin
                - ping
                - '-p${DB_ROOT_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
          - '${MYADMIN_PORT}:80'
        environment:
            PMA_HOST: 'mysqldb'
        networks:
            - mysqlnet
        depends_on:
            - mysqldb
networks:
    mysqlnet:
        driver: bridge
volumes:
    admin-mysqldb:
        driver: local
